const portfolioItems = [
  {
    id: 1,
    title: "Todo App",
    category: "Front-end / Web app",
    url: "./images/todo.png",
    bgColor: "linear-gradient(45deg, #b721ff 0%, #21d4fd 100%)",
    overlayColor: "#b721ff",
    transform: "skew(20deg) rotate(-8deg)",
    height: "48vh",
  },
  {
    id: 2,
    title: "Ice Cream",
    category: "Graphic design",
    url: "./images/11.png",
    bgColor: "linear-gradient(to right, #fa709a 0%, #fee140 100%)",
    overlayColor: "#fee140",
    transform: "skew(15deg) rotate(7deg)",
    height: "42vh",
  },
  {
    id: 3,
    title: "Bulb",
    category: "Graphic design",
    url: "./images/22.png",
    bgColor: "linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)",
    overlayColor: "#a1c4fd",
    transform: "skew(-14deg) rotate(-4deg)",
    height: "55vh",
  },
  {
    id: 4,
    title: "Gun",
    category: "Graphic design",
    url: "./images/33.png",
    bgColor: "linear-gradient(to top, #e6b980 0%, #eacda3 100%)",
    overlayColor: "#e6b980",
    transform: "skew(10deg) rotate(17deg)",
    height: "40vh",
  },
  {
    id: 5,
    title: "Drinks",
    category: "Graphic design",
    url: "./images/44.png",
    bgColor: "lightgrey",
    overlayColor: "grey",
    transform: "skew(-10deg) rotate(7deg)",
    height: "50vh",
  },
  {
    id: 6,
    title: "Nice View",
    category: "Graphic design",
    url: "./images/55.png",
    bgColor: "violet",
    overlayColor: "violet",
    transform: "skew(21deg) rotate(2deg)",
    height: "40vh",
  },
  {
    id: 7,
    title: "Smartphone",
    category: "Graphic design",
    url: "./images/fon.png",
    bgColor: "linear-gradient(to top, #00c6fb 0%, #005bea 100%)",
    overlayColor: "#005bea",
    transform: "skew(26deg) rotate(-4deg)",
    height: "55vh",
  },
  {
    id: 8,
    title: "Informatyk na godziny",
    category: "Front-end / Landing page",
    url: "./images/informatyk.png",
    bgColor: "#b3c1ed",
    overlayColor: "#2e1e5c",
    transform: "skew(-18deg) rotate(-5deg)",
    height: "50vh",
  },
];

export default portfolioItems;
