const portfolioItems = [
  {
    id: 1,
    title: "Todo App",
    category: "Front-end / Web app",
    project: {
      description:
        "Todo App is a simple tool to help you organise everything. It’s a list of tasks you need to complete or things that you want to do. This projects is a solution to the Todo app challenge on Frontend Mentor.",
      details:
        "The app is connected with Firebase and perform CRUD operations in the database. Users are able to: view the optimal layout for the app depending on their device's screen size, see hover states for all interactive elements on the page, toggle light and dark mode, add new todos to the list, mark todos as complete, update todos, delete todos from the list, filter by all/active/complete todos.",
      technology: ["React.js", "Styled Components", "Firebase", "RWD"],
    },
    url: "../images/todo.png",
    bgColor: "linear-gradient(45deg, #b721ff 0%, #21d4fd 100%)",
    overlayColor: "#b721ff",
    transform: "skew(20deg) rotate(-8deg)",
    height: "48vh",
    path: "work/todo-app",
  },
  {
    id: 2,
    title: "Ice Cream",
    category: "Graphic design",
    url: "../images/11.png",
    bgColor: "linear-gradient(to right, #fa709a 0%, #fee140 100%)",
    overlayColor: "#fee140",
    transform: "skew(15deg) rotate(7deg)",
    height: "42vh",
    path: "work/ice-cream",
  },
  {
    id: 3,
    title: "Bulb",
    category: "Graphic design",
    url: "../images/22.png",
    bgColor: "linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)",
    overlayColor: "#a1c4fd",
    transform: "skew(-14deg) rotate(-4deg)",
    height: "55vh",
    path: "work/bulb",
  },
  {
    id: 4,
    title: "Gun",
    category: "Graphic design",
    url: "../images/33.png",
    bgColor: "linear-gradient(to top, #e6b980 0%, #eacda3 100%)",
    overlayColor: "#e6b980",
    transform: "skew(10deg) rotate(17deg)",
    height: "40vh",
    path: "work/gun",
  },
  {
    id: 5,
    title: "Drinks",
    category: "Graphic design",
    url: "../images/44.png",
    bgColor: "lightgrey",
    overlayColor: "grey",
    transform: "skew(-10deg) rotate(7deg)",
    height: "50vh",
    path: "work/drinks",
  },
  {
    id: 6,
    title: "Nice View",
    category: "Graphic design",
    url: "../images/55.png",
    bgColor: "violet",
    overlayColor: "violet",
    transform: "skew(21deg) rotate(2deg)",
    height: "40vh",
    path: "work/nice-view",
  },
  {
    id: 7,
    title: "Smartphone",
    category: "Graphic design",
    url: "../images/fon.png",
    bgColor: "linear-gradient(to top, #00c6fb 0%, #005bea 100%)",
    overlayColor: "#005bea",
    transform: "skew(26deg) rotate(-4deg)",
    height: "55vh",
    path: "work/smartphone",
  },
  {
    id: 8,
    title: "Informatyk na godziny",
    category: "Front-end / Landing page",
    url: "../images/informatyk.png",
    bgColor: "#b3c1ed",
    overlayColor: "#2e1e5c",
    transform: "skew(-18deg) rotate(-5deg)",
    height: "50vh",
    path: "work/informatyk",
  },
];

export default portfolioItems;
